[config] # in configuration.toml
model = "gemini/gemini-2.5-pro-preview-03-25"
fallback_models = ["gemini/gemini-2.0-flash"]

[pr_description] # /describe #
# use_description_markers=true
# inline_file_summary='table'
keep_original_user_title = true
extra_instructions = """\
- Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `fix:`, `perf:`, `refactor:`, `test:`, `chore:`, `ci:`, `docs:` etc
"""

[pr_reviewer] # /review #
inline_code_comments = true
enable_help_text = false
extra_instructions = """\
- Please use Japanese in descriptions.
"""
