[config] # in configuration.toml
model="gemini/gemini-2.0-flash-exp"
fallback_models=["gemini/gemini-2.0-flash-exp"]

[pr_description] # /describe #
use_description_markers=true
inline_file_summary='table'
keep_original_user_title=true

[pr_reviewer] # /review #
inline_code_comments=true
enable_help_text=false
extra_instructions="""\
- 日本語でフィードバックしてください
- フィードバックはコードの修正についてであること
"""
