# inherit_from: rubocop-todo.yml

AsciiComments:
    Enabled: false

Lambda:
    Enabled: false

LineLength:
  Max: 127

ClassAndModuleChildren:
    Enabled: false

Documentation:
    Enabled: false

AndOr:
    Enabled: false

AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - bin/*
    - db/schema.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
    - vendor/*
  Rails:
    Enabled: false
