#!/bin/bash

copy_file () {
    if [ ! -f ~/$1 ]; then
        cp -rf `pwd`/$1 ~/$1
    fi
}
export -f copy_file

link_file () {
    if [ ! -f ~/$1 ]; then
        ln -s `pwd`/$1 ~/$1
    fi
}
export -f link_file

ls -A | grep -v _local | grep  -vwe README -e install -e private -e ".git" -e ".gitmodules" | xargs -I{} bash -c "link_file {}"

rm -rf .emacs.d/private
ln -s `pwd`/private ~/.emacs.d/

ls -A | grep _local | xargs -I{} bash -c "copy_file {}"

cd `pwd`/.zprezto/modules/prompt/functions/
rm -f prompt_agnoster_setup prompt_powerline_setup prompt_pure_setup
