name: 'Auto Assign'
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repository
        uses: actions/checkout@v3

      - name: check bin shell
        run: ls -1 ./bin | xargs -I{} shellcheck ./bin/{}
